---
title: "Fast 2 Fail - Week 1"
author: "Dima"
date: "`r Sys.Date()`"
output: 
  html_document: 
    number_sections: yes
    toc: yes
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(njtPredict)
library(lubridate)
opts_chunk$set(echo=FALSE,
               message=FALSE,
               prompt=FALSE,
               warning=FALSE,
               cache=FALSE)

```
# OUT OF DATE (needs updating)

# Analysis of NY - TR trains only
```{r ny_tr_data}
data("njt_trains")
delay_thresh = 10
ny_tr <- njt_trains %>% 
  filter(Scheduled_Departure_Terminal == "NY", Actual_Arrival_Terminal == "TR", Line == "CORRIDOR") %>% 
  mutate(Delay = as.numeric(difftime(Scheduled_End_Time,Actual_End_Time, units = "mins")),
                         Delay = ifelse(Delay < 0, 0, Delay),
                         is_delayed = Delay >= delay_thresh | is.na(Delay)) %>% 
  group_by(is_delayed) %>% 
  mutate(round_Time = round_date(Scheduled_Start_Time, unit = "hour"), 
         Hour = hour(round_Time))
```

Treating all trains which arrived 10+ minutes later than expected as late.  

```{r hourly_weather}
data("weather_hourly")
#Take only the first entry when more than one entry exists per hour
weather_hourly_newark <- filter(weather_hourly, WBAN == 14734) %>% mutate(round_Time = round_date(Time,unit = "hour")) %>% group_by(round_Time) %>% slice(1)
nt_hourly <- inner_join(ny_tr, weather_hourly_newark, by = "round_Time")
```

```{r alt_Timetolast}
ny_tr <- ny_tr[order(ny_tr$Scheduled_Start_Time, decreasing = FALSE),]
last_event_index <- cumsum(ny_tr$is_delayed) + 1

# shift it by one to the right
last_event_index <- c(1, last_event_index[1:length(last_event_index) - 1])

# get the dates of the events and index the vector with the last_event_index, 
# added an NA as the first date because there was no event
last_event_date <- c(as.POSIXct(NA), ny_tr[which(ny_tr$is_delayed), "Scheduled_Start_Time"])[last_event_index]

# substract the event's date with the date of the last event
ny_tr$time_tolast <- difftime(ny_tr$Scheduled_Start_Time, last_event_date, units = "mins")



```

```{r calculate_Timetolast}
nt_hourly <- nt_hourly[order(nt_hourly$Scheduled_Start_Time, decreasing = FALSE),]
nt_hourly$timeto_lastdelay <- NA
last_delay = NULL
for(i in seq(nrow(nt_hourly))){
  i_row <- nt_hourly[i,]
  if(!is.null(last_delay)){
    nt_hourly[i,"timeto_lastdelay"] <- as.numeric(difftime(i_row$Scheduled_Start_Time, last_delay, units = "mins"))
  }
  if(i_row$is_delayed)  last_delay = i_row$Scheduled_Start_Time
  # print(i/nrow(nt_hourly))
}

nt_hourly <- nt_hourly %>% 
  ungroup %>% 
  mutate(delay_30 = timeto_lastdelay <= 30,
         delay_60 = timeto_lastdelay <= 60,
         delay_90 = timeto_lastdelay <= 90)
```

```{r}
nt_hourly %>% ggplot(aes(is_delayed,timeto_lastdelay)) + geom_boxplot()
nt_hourly %>% ggplot(aes(timeto_lastdelay, fill = is_delayed)) + geom_density(alpha = 0.3)
nt_hourly %>% ggplot(aes(delay_60, Delay)) + geom_boxplot()

nt_hourly %>% ggplot(aes(timeto_lastdelay)) + geom_density() + facet_wrap(~is_delayed) + xlim(0,400)
```


```{r}
glm(formula = is_delayed~Scheduled_Start_Time+as.numeric(DryBulbFarenheit)+as.numeric(HourlyPrecip)+delay_60, nt_hourly_hist, family="binomial") %>% summary

glm(formula = is_delayed~Scheduled_Start_Time+as.numeric(DryBulbFarenheit)+as.numeric(HourlyPrecip)+timeto_lastdelay, nt_hourly, family="binomial") %>% summary


glm(formula = is_delayed~as.numeric(DryBulbFarenheit)+as.numeric(HourlyPrecip), nt_hourly_hist, family="binomial") %>% summary

# m <- glm(formula = is_delayed~as.numeric(Tavg)+as.numeric(PrecipTotal)+SnowFallFlag, data = nt_merge, family = "binomial")
summary(m)
```

```{r}
nt_hourly_hist %>% group_by(is_delayed, delay_60) %>% tally %>% .$n  %>% matrix(, nrow = 2)  %>% fisher.test()
nt_hourly_hist %>% group_by(is_delayed, delay_90) %>% tally %>% .$n  %>% matrix(, nrow = 2)  %>% chisq.test()

```

```{r}
library(caret)
train_control <- trainControl(method="cv", number=10)
train_data <- nt_hourly %>% ungroup %>% 
  select(is_delayed, Scheduled_Start_Time, DryBulbFarenheit, timeto_lastdelay) %>% 
  mutate(is_delayed = factor(is_delayed), DryBulbFarenheit = as.numeric(DryBulbFarenheit)) %>% 
  mutate(delay_60 = timeto_lastdelay <= 60) %>% select(-timeto_lastdelay)
fit <- train(is_delayed~., data = train_data, method = "glm", family = "binomial", trControl = train_control)
fit2 <- train(is_delayed~., data = train_data, method = "nb", trControl = train_control)
predictions <-  predict(fit, train_data[,2:4])
confusionMatrix(predictions, (train_data$is_delayed))
```


#OLD  
Space is used while a formal github is not yet in place
```{r}
data("weather_daily")

weather_daily_newark <- filter(weather_daily, WBAN == 14734)
nt_daily <- inner_join(ny_tr, weather_daily_newark, by = c("Run_Date" = "YearMonthDay"))

test <- nt_daily %>% mutate(is_precip = as.numeric(PrecipTotal) > 5)
table(as.numeric(weather_daily_newark$PrecipTotal) > 5)
```

```{r}
# delay_vec <- nt_hourly$is_delayed
# names(delay_vec) <- paste0(nt_hourly$Scheduled_Start_Time)
# 
# minute_range = 60



# df <- nt_hourly  %>% filter(Run_Date == "2010-01-01")
calculateHistDelays <- function(df){
  delay_vec = df$is_delayed
  names(delay_vec) = df$Scheduled_Start_Time
  delay_30 <- sapply(df$Scheduled_Start_Time, function(end)
    any(delay_vec[which(names(delay_vec) < end & names(delay_vec) >= end - 60 * 30)]))
  delay_60 <- sapply(df$Scheduled_Start_Time, function(end)
    any(delay_vec[which(names(delay_vec) < end & names(delay_vec) >= end - 60 * 60)]))
  delay_90 <- sapply(df$Scheduled_Start_Time, function(end)
    any(delay_vec[which(names(delay_vec) < end & names(delay_vec) >= end - 60 * 90)]))
  data.frame("delay_30" = delay_30, "delay_60" = delay_60, "delay_90" = delay_90)
}
hist_delays <- nt_hourly %>% group_by(Run_Date) %>% 
  do(calculateHistDelays(.))

nt_hourly_hist <- cbind(nt_hourly, hist_delays[,-1])

```


```{r}
nt_hourly <- nt_hourly[order(nt_hourly$Scheduled_Start_Time, decreasing = TRUE),]
delay_vec = nt_hourly$is_delayed
names(delay_vec) = nt_hourly$Scheduled_Start_Time
# 
# a <- delay_vec
# b <- a[a==TRUE]
# # c <- rep(a,time = length(b))
# Approach from Sach building a rep matrix

# Very inelegant solution
nt_hourly$timeto_lastdelay <- sapply(seq_along(delay_vec), function(i){
  current_Time = names(delay_vec[i])
  found_delay = FALSE
  next_i = i
  if(i > length(delay_vec)-5){ #Hacky fix, need to better handle
    return(NA)
  }
  else{
    while(!found_delay){
      next_i = next_i + 1
      found_delay = delay_vec[next_i]
      if(next_i-i>5){
        return(NA)
      } 
    }
    delay_Time = names(found_delay)
    dist_to_delay = as.numeric(difftime(current_Time, delay_Time, units="mins"))
    return(dist_to_delay)
  }
})
```


# For Presentation  
```{r}
library(xkcd)
# , outlier.shape = NA
ggplot() + geom_boxplot(aes(x = delay_60,y = Delay),data = nt_hourly) + 
  xkcdaxis(xrange = c(0.5,2.5),yrange = range(nt_hourly$Delay, na.rm = TRUE),jitteramount=.1) + 
  theme(title = element_text(size = 12)) + xlab("Previous Delay Less Than 60 Minutes") + coord_flip()
```

```{r}
set.seed(42)
ggplot() + 
  xkcdaxis(xrange = c(0,400),yrange = c(0,0.004),jitteramount=.05) +
  # geom_density(aes(timeto_lastdelay, color = is_delayed), data = nt_hourly) +
  geom_line(aes(timeto_lastdelay, color = is_delayed), data = nt_hourly, stat = "density", size = 1.2) +
  xlab("Time To Last Delay") + ylab("") +
  scale_color_discrete(name = "Is Delayed")
  # geom_hline(yintercept=0, colour="white", size=1)
# + facet_wrap(~is_delayed) + xlim(0,400)
```


```{r}
nt_hourly %>% count(delay_60, is_delayed)

tmp <- nt_hourly  %>% mutate(is_rush = hour(Scheduled_Start_Time) %in% c(7:9,16:18))

tmp %>% count(is_rush, is_delayed)
```

